### ISSUE TITLE
sleep lib is pulling in deno stdlib from bleeding edge, causing TS18022 ERROR

### ISSUE THREAD

**Issue by grempe** [michael-spengler/sleep#2]
Due to preparatory changes in v0.98.0 of the Deno stdlib, and the fact that this lib is pulling in the `log` lib without a version number of stdlib to use, this lib is causing breaking changes for users.

See this issue for the cause of the breakage.

https://github.com/denoland/deno/issues/10799#issuecomment-854019680

Please remove the logging statement which probably doesn't belong in this lib, or pin the stdlib to a specific version.

Thanks.

**Comment by grempe** [comment]
This was also addressed in this fork of `sleep` for exactly this reason.

https://github.com/ngruychev/sleep/commit/048f1b762848122c9d0fea181acc9222a75fb8e0

**Comment by michael-spengler** [comment]
@grempe: sorry for the extremely late response from my side - sometimes I loose track about my open source github account... or I just slept tooooo long :) 

--> PR merged now + created / published a new release: https://deno.land/x/sleep v1.2.1

**Comment by grempe** [comment]
Thanks for the merge and release.
